### ISSUE TITLE
Add user account management

### ISSUE THREAD

**Issue by ejmockler** [communisaas/communique-site#10]
## Background
Users need to be able to manage data and their accounts.

## Tasks

- [x] Account page
  - [ ] Change address
  - [ ] Edit ignored content list
  - [x] Close account
- [ ] Handle switching oauth providers
   - [ ] Detect duplicate email addresses
