### ISSUE TITLE
Basic geolocation

### ISSUE THREAD

**Issue by ejmockler** [communisaas/communique-site#17]
## Background
Some email templates address representatives of a specific geographical constituency—give options to tag emails by location & include senders' physical addresses in the message.

## Tasks

- [x] Rough timezone/country matcher
- [x] Profile option to add physical address
- [x] Template location tagging
  - [x] Worldwide city, state, country autocomplete (latin characters, EN locale to start) 
- [ ] Autofill sender's physical address at bottom of template from user account
